name: model-wine-quality
on: [push]
jobs: 
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          repo_token: ${{ secrets.GITHUB }}
        run: |
          pip install -r requirements.txt
          python train.py
          
          echo "## MODEL METRICS" > report.md
          cat metrics.txt >> report.md

          cml comment create report.md
          
